#!/bin/sh
 
pipewire &
pipewire-pulse &
wireplumber &
mako &
foot --server &

if [ -x "/usr/libexec/polkit-gnome-authentication-agent-1" ]; then
    /usr/libexec/polkit-gnome-authentication-agent-1 &
fi

# exec dbus-update-environment WAYLAND_DISPLAY
